DROP TABLE IF EXISTS `phpcms_ziyuan`;
CREATE TABLE `phpcms_ziyuan` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `realname` varchar(256) NOT NULL,
  `sex` varchar(128) NOT NULL,
  `product` varchar(256) NOT NULL,
  `pronum` varchar(256) NOT NULL,
  `address`  varchar(256) NOT NULL,
  `tel` varchar(256) NOT NULL,
  `tel2` varchar(256) NOT NULL,
  `qq` varchar(256) NOT NULL,
  `mail` varchar(256) NOT NULL,
  `tzjy_one` varchar(256) NOT NULL,
  `zijin` varchar(256) NOT NULL,
  `bank_account_name` varchar(256) NOT NULL,
  `bank_name` varchar(256) NOT NULL,
  `bank_account` varchar(256) NOT NULL,
  `file1` varchar(256) NOT NULL,
  `pic1` varchar(256) NOT NULL,
  `file11` varchar(256) NOT NULL,
  `pic2` varchar(256) NOT NULL,
  `file2` varchar(256) NOT NULL,
  `pic3` varchar(256) NOT NULL,
  `file3` varchar(256) NOT NULL,
  `pic4` varchar(256) NOT NULL,
  `postscript` varchar(256) NOT NULL,
  `x` varchar(256) NOT NULL,
  `y` varchar(256) NOT NULL,
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
