<?php exit;?>11-28 09:14:13 | 2 | chmod(): Operation not permitted | phpcms/modules/content/classes/html.class.php | 364
<?php exit;?>11-28 15:22:11 | 2 | mkdir(): Permission denied     | phpcms/libs/functions/dir.func.php | 30
<?php exit;?>11-28 15:22:11 | 2 | chmod(): No such file or directory | phpcms/libs/functions/dir.func.php | 31
<?php exit;?>11-28 15:22:38 | 2 | mkdir(): Permission denied     | phpcms/libs/functions/dir.func.php | 30
<?php exit;?>11-28 15:22:38 | 2 | chmod(): No such file or directory | phpcms/libs/functions/dir.func.php | 31
<?php exit;?>11-28 15:23:00 | 2 | mkdir(): Permission denied     | phpcms/libs/functions/dir.func.php | 30
<?php exit;?>11-28 15:23:00 | 2 | chmod(): No such file or directory | phpcms/libs/functions/dir.func.php | 31
<?php exit;?>11-29 12:03:50 | 2 | chmod(): Operation not permitted | phpcms/modules/content/classes/html.class.php | 364
<?php exit;?>11-29 15:26:13 | 2 | rmdir(/home/kaleo/www/default/phpcms/templates/default/ziyuan/): Directory not empty | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>11-29 19:49:43 | 2 | rmdir(/home/kaleo/www/default/phpcms/templates/default/ziyuan/): Not a directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>11-29 20:12:39 | 2 | rmdir(/home/kaleo/www/default/phpcms/templates/default/ziyuan/): Not a directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-01 11:10:29 | 2 | file_put_contents() expects at least 2 parameters, 1 given | phpcms/modules/ziyuan/upload.php | 18
<?php exit;?>12-01 11:12:56 | 2 | move_uploaded_file(): Filename cannot be empty | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 11:12:56 | 2 | move_uploaded_file(): Unable to move '/tmp/phpqucxvb' to '' | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 11:13:32 | 2 | move_uploaded_file(): Filename cannot be empty | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 11:13:32 | 2 | move_uploaded_file(): Unable to move '/tmp/phpmjhAMs' to '' | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 11:26:42 | 2 | move_uploaded_file(): Filename cannot be empty | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 11:26:42 | 2 | move_uploaded_file(): Unable to move '/tmp/phplyZsoy' to '' | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 11:29:49 | 2 | move_uploaded_file(): Filename cannot be empty | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 11:29:49 | 2 | move_uploaded_file(): Unable to move '/tmp/phpDoit20' to '' | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 11:30:10 | 2 | move_uploaded_file(): Filename cannot be empty | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 11:30:10 | 2 | move_uploaded_file(): Unable to move '/tmp/phpbXyZrW' to '' | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 11:30:38 | 2 | move_uploaded_file(): Filename cannot be empty | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 11:30:38 | 2 | move_uploaded_file(): Unable to move '/tmp/phpW4Nihn' to '' | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 13:03:43 | 2 | move_uploaded_file(): Filename cannot be empty | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 13:03:43 | 2 | move_uploaded_file(): Unable to move '/tmp/phplxNIw3' to '' | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 13:10:57 | 2 | move_uploaded_file(): Filename cannot be empty | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-01 13:10:57 | 2 | move_uploaded_file(): Unable to move '/tmp/php6eGRzM' to '' | phpcms/modules/ziyuan/upload.php | 17
<?php exit;?>12-05 10:59:36 | 2 | rmdir(/home/kaleo/www/default/phpcms/templates/default/ziyuan/): Not a directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-05 11:13:19 | 2 | chmod(): Operation not permitted | phpcms/modules/content/classes/html.class.php | 364
<?php exit;?>12-05 13:22:34 | 2 | chmod(): Operation not permitted | phpcms/modules/content/classes/html.class.php | 364
<?php exit;?>12-05 13:39:07 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-05 13:45:59 | 2 | chmod(): Operation not permitted | phpcms/modules/content/classes/html.class.php | 364
<?php exit;?>12-05 14:20:50 | 2 | rmdir(/home/kaleo/www/default/phpcms/templates/default/ziyuan/): Not a directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-05 14:34:54 | 2 | chmod(): Operation not permitted | phpcms/modules/content/classes/html.class.php | 364
<?php exit;?>12-05 14:36:03 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-05 15:46:30 | 2 | require_once(/home/kaleo/www/default/phpcms/modules/okrobot/classes/okcoin.class.php): failed to open stream: No such file or directory | phpcms/modules/okrobot/index.php | 3
<?php exit;?>12-05 15:50:26 | 4096 | Object of class stdClass could not be converted to string | phpcms/modules/okrobot/index.php | 20
<?php exit;?>12-05 15:50:28 | 4096 | Object of class stdClass could not be converted to string | phpcms/modules/okrobot/index.php | 20
<?php exit;?>12-05 16:52:39 | 2 | simplexml_load_string() expects parameter 1 to be string, object given | phpcms/modules/okrobot/index.php | 20
<?php exit;?>12-05 17:02:26 | 2 | simplexml_load_string() expects parameter 1 to be string, object given | phpcms/modules/okrobot/index.php | 20
<?php exit;?>12-06 11:39:44 | 2 | chmod(): Operation not permitted | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>12-06 11:39:44 | 2 | chmod(): Operation not permitted | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 11:39:49 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 11:41:47 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 11:41:47 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 11:41:47 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 11:41:47 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 11:41:47 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 11:41:47 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 11:41:47 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 11:41:47 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 11:41:48 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 11:41:48 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 11:41:48 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 11:41:48 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:28:06 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:28:06 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:28:06 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:28:06 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:28:06 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:28:06 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:28:06 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:28:06 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:28:07 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:28:07 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:28:07 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:28:07 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:28:23 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:28:23 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:28:23 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:28:23 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:28:23 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:28:23 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:28:23 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:28:23 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:28:24 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:28:24 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:28:24 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:28:24 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:47:20 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:47:20 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:47:20 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:47:20 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 12:47:21 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:47:21 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:47:21 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:47:21 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 12:47:21 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:47:21 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:47:21 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 12:47:21 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/languages/zh-cn/okrobot.lang.php): Permission denied | phpcms/modules/admin/classes/module_api.class.php | 187
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 16:13:17 | 2 | file_put_contents(/home/kaleo/www/okrobot/phpcms/templates/default/config.php): failed to open stream: Permission denied | phpcms/modules/admin/classes/module_api.class.php | 197
<?php exit;?>12-06 16:13:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 16:13:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 16:13:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 16:13:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 16:13:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 16:13:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 16:13:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 16:13:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 16:13:20 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 16:13:20 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 16:13:20 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 16:13:20 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 16:13:23 | 2 | mkdir(): Permission denied     | phpcms/libs/functions/dir.func.php | 30
<?php exit;?>12-06 16:13:23 | 2 | chmod(): No such file or directory | phpcms/libs/functions/dir.func.php | 31
<?php exit;?>12-06 16:14:21 | 2 | mkdir(): Permission denied     | phpcms/libs/functions/dir.func.php | 30
<?php exit;?>12-06 16:14:21 | 2 | chmod(): No such file or directory | phpcms/libs/functions/dir.func.php | 31
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | copy(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/index.html): failed to open stream: Permission denied | phpcms/libs/functions/dir.func.php | 54
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Operation not permitted | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:51 | 2 | copy(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates): failed to open stream: Is a directory | phpcms/libs/functions/dir.func.php | 54
<?php exit;?>12-06 16:14:51 | 2 | chmod(): Too many levels of symbolic links | phpcms/libs/functions/dir.func.php | 55
<?php exit;?>12-06 16:14:55 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 16:14:55 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 16:14:55 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 16:14:55 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 16:14:55 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 16:14:55 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 16:14:55 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 16:14:55 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 16:14:56 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 16:14:56 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 16:14:56 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 16:14:56 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:44:51 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:44:51 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:44:51 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:44:51 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:44:51 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:44:51 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:44:51 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:44:51 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:44:52 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:44:52 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:44:52 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:44:52 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:45:15 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/templates/): No such file or directory | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:45:15 | 2 | file_put_contents(/home/kaleo/www/okrobot/phpcms/templates/default/config.php): failed to open stream: Permission denied | phpcms/modules/admin/classes/module_api.class.php | 197
<?php exit;?>12-06 17:45:17 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:45:17 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:45:17 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:45:17 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:45:18 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:45:18 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:45:18 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:45:18 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:45:19 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:45:19 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:45:19 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:45:19 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:46:17 | 2 | unlink(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/index.html): Permission denied | phpcms/libs/functions/dir.func.php | 152
<?php exit;?>12-06 17:46:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/templates/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:46:17 | 2 | rmdir(/home/kaleo/www/okrobot/phpcms/templates/default/okrobot/): Permission denied | phpcms/libs/functions/dir.func.php | 154
<?php exit;?>12-06 17:46:17 | 2 | file_put_contents(/home/kaleo/www/okrobot/phpcms/templates/default/config.php): failed to open stream: Permission denied | phpcms/modules/admin/classes/module_api.class.php | 197
<?php exit;?>12-06 17:46:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:46:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:46:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:46:19 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 273
<?php exit;?>12-06 17:46:20 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:46:20 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:46:20 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:46:20 | 2 | chmod(): Operation not permitted | phpcms/modules/admin/classes/cache_api.class.php | 394
<?php exit;?>12-06 17:46:21 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:46:21 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:46:21 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
<?php exit;?>12-06 17:46:21 | 2 | chmod(): Operation not permitted | phpcms/modules/formguide/classes/formguide.class.php | 35
